# These are supported funding model platforms
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: lAvArt
# ko_fi: 
# patreon: 
# custom: ["https://pluragate.org/donate"]
